force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro.</description>
    <label>Mercado</label>
    <nameField>
        <label>Nome de Mecardo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mercado__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <summarizedField>Ordem__c.QuandtidadeP__c</summarizedField>
    <summaryForeignKey>Ordem__c.Mecardo__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Numero da Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da execução da ordem</description>
    <inlineHelpText>Status da execução da ordem</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando</fullName>
                <default>true</default>
                <label>Aguardando</label>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Venda com lucro</fullName>
            </value>
            <value>
                <fullName>Venda com prejuízo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ordem__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Identifica se a ordem é do tipo compra ou venda</description>
    <inlineHelpText>Identifica se a ordem é do tipo compra ou venda</inlineHelpText>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compra</fullName>
            </value>
            <value>
                <fullName>Venda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VFOrderController.cls
public class VFOrderController {
    
    public List<Ordem__c> ordemList {get; set;}
    public String currentValue {get; set;}

    public VFOrderController(){
        
    }

    public VFOrderController(ApexPages.StandardController controller){
        Mercado__c mercado = (Mercado__c) controller.getRecord();

        //mercad.Name
        //mecado.Id
        
        ordemList = [SELECT Id, Name, OperacaoMercado__c, Preco__c, Tipo__c, Status__c, Quantidade__c, Total__c, Validade__c 
                     FROM Ordem__c 
                     WHERE Mercado__c =:mercado.Id
                    ];
        currentValue = BinanceAPI.getPrice(mercado.Id);
    }
}